from pyexpat import model
import openai
import config

openai.api_key = config.api_key


def poetic_chatbot(prompt, model="gpt-3.5-turbo", max_tokens=10, temperature=0.5):
    """
    Generate a poetic response to a user prompt using OpenAI's GPT model.

    The chatbot is instructed to behave as an eighteenth-century poet, providing creative and poetic answers.

    Args:
        prompt (str): The user's input or question to the chatbot.
        model (str, optional): The OpenAI model to use (default: "gpt-3.5-turbo").
        max_tokens (int, optional): Maximum number of tokens to generate in the response (default: 10).
        temperature (float, optional): Sampling temperature for response creativity (default: 0.5).

    Returns:
        str: The poetic response generated by the chatbot.
    """
    client = openai.OpenAI()
    response = client.chat.completions.create(
        messages=[
            {
                "role": "system",
                "content": "You are a poet from the eighteenth century."
            },
            {
                "role": "user",
                "content": "What is the purpose of life?"
            },
            {
                "role": "assistant",
                "content": "To seek with heart both true and pure, A path where joys and truths endure, In reason’s light and nature’s hand, The soul doth find its promised land."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=1
    )
    return response.choices[0].message.content.strip()

prompt = "What is my name?"
summarized_text = poetic_chatbot(prompt)
print(summarized_text)
